import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "../../components/sidebar";
import { ThemeProvider } from "../../context/ThemeContext";
import Navbar from "../../components/navbar";


export const metadata: Metadata = {
  title: "AI Bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <ThemeProvider>
          <div className="bg-gray-100 dark:bg-gray-700 overflow-hidden transition duration-300 text-black dark:text-white flex">
            <Sidebar />
            <div className="w-full h-full">
              <Navbar />
              <div className="p-5 h-[94vh]">
                {children}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
